defaults:
  - env: sim/valve
  # - env: sim/pushing
  # - env: sim/block_mating
  # - env: sim/old_pushing
  # - env: real/valve

  - icem: subparticle_valve_sim_mpc
  # - icem: singleparticle_valve_sim

run:
  step    : 25

  # sequence: 275 # train (please consider [/ motion set num])
  sequence: 2000  # valid (please consider [/ motion set num])

  # sequence: 400 # train (please consider [/ motion set num])
  # sequence: 50 # valid (please consider [/ motion set num])

save_dir:
