defaults:
  # - env: sim/valve
  # - env: sim/block_mating
  - env: sim/pushing
  # - env: sim/old_pushing
  # - env: real/valve

run:
  step    : 25

  # sequence: 275 # train (please consider [/ motion set num])
  sequence: 5 # valid (please consider [/ motion set num])

  # sequence: 400 # train (please consider [/ motion set num])
  # sequence: 50 # valid (please consider [/ motion set num])
