# << general >>
num_cem_iter               : 5
planning_horizon           : 10
dim_action                 : 3
dimension_of_interst       : [0, 1, 2]

colored_noise_exponent     : 3.5

lower_bound_sampling       :  0.0
upper_bound_sampling       :  0.1
lower_bound_cusum_action   : # None
upper_bound_cusum_action   : # None
lower_bound_simulated_path : -1.0
upper_bound_simulated_path : 6.283185307179586
dim_path                   : 1

# << sampling >>
num_sample                 : 1000
decay_sample               : 1.25

# << elite >>
num_elite                  : 3
fraction_rate_elite        : 1.0

# << update distribution >>
alpha                      : 0.5 # save rate of previous mean
init_std                   : 0.75

# << other >>
debug                      : False
verbose                    : True
verbose_additional         : False
save_visualization_dir     : "./fig"
is_verbose_newline         : True
